### ISSUE TITLE
AttributeError: module 'edaviz' has no attribute 'plot'

### ISSUE THREAD

**Issue by jefferyansah** [tkrabel/edaviz#2]

**Comment by tkrabel** [comment]
Hi @vanslerry,

can you tell me the following two things:

- what do you get if you type `import edaviz; edaviz`?
- what edaviz version you are using?

Best,
Tobias

**Comment by jefferyansah** [comment]
Version 0.0.0

I don't get any error when Import edaviz.

I have pip installed and uninstalled several times still not working

**Comment by tkrabel** [comment]
Version 0.0.0 is a dummy version on pypi. edaviz is currently in private access mode.

If you want to get access to the real edaviz version, please [subscribe to our mailing list](http://eepurl.com/go6Zlj). You will then get immediate access.

**Comment by jefferyansah** [comment]
I have subscribed to the mailing list and I have been given a subscription
key.

I have followed all the instructions as required in the final email after
filling the survey.

**Comment by tkrabel** [comment]
I pm you

**Comment by tina3005** [comment]
i faced the same issue,and i have subscribed to the mailing list, but do not get a subscription key ,could you please sugguest?
