### ISSUE TITLE
Still getting edaviz version 0.0.0 

### ISSUE THREAD

**Issue by jefferyansah** [tkrabel/edaviz#3]
I used the command below put I am still getting the version 0.0.0

**Comment by vanslerry** [comment]
![edaviz](https://user-images.githubusercontent.com/11032604/61673136-a2edb180-ad31-11e9-8de9-67c9b2f53da7.PNG)

**Comment by tkrabel** [comment]
Just to clarify the issue for users how might see this: **You need Python version 3.6+** in order to use edaviz. If you pip install it (using our private pip command) with a lower python version, the install will fail. In this case, pip then downloads edaviz 0.0.0 from pypi.
